### ISSUE TITLE
error of no compatible GPUs 

### ISSUE THREAD

**Issue by sheru18** [vertiond/verthash-one-click-miner#102]
hello,
As I was running the Verthash one click miner but a suddenly a error comes of no compatible GPUs as it was running nice before but suddenly it came so please tell me the solution how to solve it so that I could run my miner and can earn from it
I will be waiting for this kind consideration
Regards,

![Desktop Screenshot 2022 02 26 - 19 32 19 31](https://user-images.githubusercontent.com/100478569/155847010-1b48e358-facb-4e54-b3da-b0d951614ae8.png)

**Comment by sheru18** [comment]
but my GPU drivers are upto date so this is an another issue so please tell me a solution of it
![Desktop Screenshot 2022 02 26 - 22 30 40 44](https://user-images.githubusercontent.com/100478569/155853135-ce28697f-3d10-4664-a2e1-abb622a44b70.png)

**Comment by vertiond** [comment]
Revisit antivirus exclusions?  Check the FAQ

**Comment by sheru18** [comment]
I have check that also. That is an another problem so if u have any solution then please tell me 
Thanks

**Comment by vertiond** [comment]
Please join Discord for personal support https://discord.gg/vertcoin
