### ISSUE TITLE
Verthash OCM is mining, but all balances are still 0, and it does not appear in Task Mgr - no use of resources detected

### ISSUE THREAD

**Issue by VioletBlue007** [vertiond/verthash-one-click-miner#111]
Verthash OCM installed and launched, but I don't see it in Task Manager. Also all balances on the Wallet page are still 0.

Expected to see the Verthash OCM app in tas mgr and the balance to slowly go up

OCM v2.15-0-gc30cd9d (from GitHub)

Predator Helios 300 gaming laptop, Windows 10, GeForce RTX 3070 (8GB dedicated VRAM)

![Verthash not mining](https://user-images.githubusercontent.com/100283769/165849826-90a598ec-d7ff-4474-a624-4c77975f0eb6.jpg)

**Comment by vertiond** [comment]
You probably have to mine a bit longer to see a pending balance.  VerthashMiner.exe is the process you would be looking for.  Resource usage is available: Check for CUDA usage if you have a nvidia card and Compute 0/1 if you have a AMD.
