### ISSUE TITLE
Problem of sending.backend_failure

### ISSUE THREAD

**Issue by gurinder453** [vertiond/verthash-one-click-miner#133]
Hi sir,
I am facing a problem when I try to withdraw my funds. It shows sending.backend_failure.
Please help me, screenshot attached below

![Screenshot (11)](https://user-images.githubusercontent.com/116021397/196235632-ade60065-5e97-4f96-a1a6-987bd9c61653.png)

Sincerely,
Maneetinder Singh

**Comment by vertiond** [comment]
Please re-open if this still persists
