### ISSUE TITLE
failed to configure, exit status 1, Debian 11

### ISSUE THREAD

**Issue by KoryMac** [vertiond/verthash-one-click-miner#15]
Checks failed:
Failure to configure VerthashMiner: exit status 1

I'm trying to run this in Debian 11 on an intel i5-3470. I don't have a compatible graphics card; I'm guessing that this may have something to with it. I know that the program was able to access my iGPU, because I got 
"libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0"
as output in my terminal. 

The last few lines of output I got before this error message was displayed were:
"2021/03/25 20:59:14.183420 [DEBUG] [Miner linux/3]Daemon file is available and correct
2021/03/25 20:59:14.183498 [DEBUG] [Miner linux/3](Re)creating unpack directory
2021/03/25 21:05:50.990921 [DEBUG] Launching /root/.verthash-ocm/miners/unpacked-e451aa55e05a30398728f658d9990caf48b982afc5422d98183dbbde4fd0fa8a/VerthashMiner-0.7.0-CUDA11-linux/VerthashMiner [--gen-conf /root/.verthash-ocm/verthash-miner-tmpl.conf]".

Does this miner only do GPU mining and not CPU mining, and is this the reason for this error?

**Comment by zentros** [comment]
I'm pretty sure verthash OCM only does gpu mining, either on a dedicated graphics card or on a integrated gpu. If you have neither of those, that's what might be causing the problem
