### ISSUE TITLE
Hangs on launch 'Estimating' & doesn't show ETH being mined

### ISSUE THREAD

**Issue by cr9cristiano** [vertiond/verthash-one-click-miner#152]
It will hang upon launch saying 'Estimating...' , then after a few minutes it will only mine VTC. No longer shows approx ETH being mined. 
 I expected it to launch in a few seconds as expected upon startup of PC. Vertcoin OCM works as expected while VertHash OCM does not, and they both launch on startup. 

 WIndows 10,  RTX 3070

 Perhaps windows defender quarantined require files or a folder. And if so how can I completely reinstall the OCM a new? There is no listed protection history showing any quarantine however so I am at a loss really. 
![Screenshot (102)](https://user-images.githubusercontent.com/83736068/228100513-415c62d0-1faf-48ef-9c3c-d007524c8020.png)
![Screenshot (103)](https://user-images.githubusercontent.com/83736068/228100538-2ecbb63f-c2b8-40aa-8d1c-0a2e8498bd82.png)

**Comment by cr9cristiano** [comment]
Forget to mention its the current 2.1.5 version of Verthash OCM

**Comment by vertiond** [comment]
Showing VTC being mined is only a graphical error that will be fixed in an upcoming release. You can verify that ETH is being paid out on Zergpool.

**Comment by cr9cristiano** [comment]
Much obliged V. Thanks for the quick update on the issue.
