### ISSUE TITLE
zergpool.com

### ISSUE THREAD

**Issue by pinpins** [vertiond/verthash-one-click-miner#21]
Hi,

1. We are lowering thresholds for DOGE 50 and 10 on Sunday accordingly.
2. Would appreciate you can consider also adding regional stratum server support(eu,na and asia)

Thank you!

**Comment by anishghimire603** [comment]
how much are you lowering the thresholds for DOGE?

**Comment by vertiond** [comment]
I believe that verthash.mine.zergpool.com:4534 is Anycast IP?

**Comment by maxperata** [comment]
please someone help, i got sent 24 dogecoins to my wallet from verthash one click miner and have no clue how to take them out from that wallet. Im using zergpool

**Comment by vertiond** [comment]
@maxperata use the Send Coins (DOGE) tab to send to any Dogecoin address of your choosing.

**Comment by maxperata** [comment]
Thanks. It's solved already. I tried that but since it was the first time I
didnt know that the transaccion took 4 hours to apear in my personal
wallet. Thanks for answering pretty fast also. Means someone is the there
to help you while in trouble.
