### ISSUE TITLE
Minier Doge coin

### ISSUE THREAD

**Issue by sAx969** [vertiond/verthash-one-click-miner#26]
Hi Goodmorning,
I want to understand why, the payment remains pending and is not inserted in the available salfo to be able to download it in my Wallet, am I wrong?

thank you very much for your attention

sAx

-->
![image](https://user-images.githubusercontent.com/80945446/119316098-d4f63480-bc76-11eb-9b80-b90e4b7e40b2.png)

**Comment by vertiond** [comment]
Pending balance must reach the payout threshold on Zergpool.  Click 'View payout information' to see the amount.
