### ISSUE TITLE
GPU Detection Error! 

### ISSUE THREAD

**Issue by a7vvmd** [vertiond/verthash-one-click-miner#28]
The issue is the Miner Software did not detect the DEDECATED 
 
the miner only Detect the built in Graphic card, Intel 620 only , not my AMD Card 
I am Using Laptop not Desktop 

i am Already Updated the Drivers from the Official Website  

i am Using The Verthash miner Ver. verthash-ocm-2.0-rc7-windows-x64
GPU Not Detected 

[debug.log](https://github.com/vertiond/verthash-one-click-miner/files/6568992/debug.log)

!--- This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred. You can find the One-Click Miner's debug log in the following place:

%APPDATA%\vertcoin-ocm on Windows
$HOME/.vertcoin-ocm on Linux

-->

**Comment by vertiond** [comment]
Your hardware is not supported
https://github.com/vertiond/verthash-one-click-miner#which-gpus-are-supported
