### ISSUE TITLE
Is dont work to mine 

### ISSUE THREAD

**Issue by elvasi** [vertiond/verthash-one-click-miner#31]

**Comment by elvasi** [comment]
Failure to configure VerthasMiner.exe: Cannot find main miner binary in unpack folder
And i dezactivet antivirus and still dont work pls help me and this problem is and for Unminer and Salad miner i dont no what to do

**Comment by vertiond** [comment]
Please read the [FAQ](https://github.com/vertiond/verthash-one-click-miner#i-have-an-error-message-that-reads-failure-to-configure)
