### ISSUE TITLE
Not working on DELL Laptop with Nvidia Geforce GT 555M

### ISSUE THREAD

**Issue by harerama21** [vertiond/verthash-one-click-miner#32]
Not working on DELL Laptop with Nvidia Geforce GT 555M

Überprüfung fehlgeschlagen: Miner Software reported no compatible GPUs

OCM v2.0-rc7

Windows 10 Laptop   Nvidia Geforce GT 555M

 https://pastebin.com/iXRnTHfs

**Comment by harerama21** [comment]
I turned on mine on integrated grafics but no success.
This is the log after turning on debugging:
2021/06/09 17:26:32.862317 OCM v2.0-rc7-c5f7bf0 Started up
2021/06/09 17:26:32.864496 [INFO] Error reading keyfile: open C:\Users\user\AppData\Roaming\verthash-ocm\dogekeyfile.hex: The system cannot find the file specified.
2021/06/09 17:26:33.170673 [INFO] User IETF is de-DE
2021/06/09 17:26:33.170673 [INFO] Matched tag is de-u-rg-dezzzz
2021/06/09 17:26:33.170673 [INFO] Returning locale de
2021/06/09 17:26:33.263793 [INFO] Checking wallet..
2021/06/09 17:26:33.263793 [INFO] Error reading keyfile: open C:\Users\user\AppData\Roaming\verthash-ocm\dogekeyfile.hex: The system cannot find the file specified.
2021/06/09 17:26:33.263793 [INFO] Error reading keyfile: open C:\Users\user\AppData\Roaming\verthash-ocm\dogekeyfile.hex: The system cannot find the file specified.
2021/06/09 17:26:33.264316 [INFO] Error reading keyfile: open C:\Users\user\AppData\Roaming\verthash-ocm\dogekeyfile.hex: The system cannot find the file specified.
2021/06/09 17:26:33.264316 [INFO] Initializing wallet DMbDViy1z4gweDFaYCyayvnPFUERB5Hymk
2021/06/09 17:26:33.264836 [INFO] Wallet initialized: 0
2021/06/09 17:26:38.253964 [INFO] Error reading keyfile: open C:\Users\user\AppData\Roaming\verthash-ocm\dogekeyfile.hex: The system cannot find the file specified.
2021/06/09 17:26:43.250513 [INFO] Error reading keyfile: open C:\Users\user\AppData\Roaming\verthash-ocm\dogekeyfile.hex: The system cannot find the file specified.
2021/06/09 17:26:48.269337 [INFO] Error reading keyfile: open C:\Users\user\AppData\Roaming\verthash-ocm\dogekeyfile.hex: The system cannot find the file specified.
2021/06/09 17:26:53.276363 [INFO] Error reading keyfile: open C:\Users\user\AppData\Roaming\verthash-ocm\dogekeyfile.hex: The system cannot find the file specified.
2021/06/09 17:26:58.292746 [INFO] Error reading keyfile: open C:\Users\user\AppData\Roaming\verthash-ocm\dogekeyfile.hex: The system cannot find the file specified.
2021/06/09 17:27:03.314785 [INFO] Error reading keyfile: open C:\Users\user\AppData\Roaming\verthash-ocm\dogekeyfile.hex: The system cannot find the file specified.
2021/06/09 17:27:08.336558 [INFO] Error reading keyfile: open C:\Users\user\AppData\Roaming\verthash-ocm\dogekeyfile.hex: The system cannot find the file specified.
2021/06/09 17:27:13.336476 [INFO] Error reading keyfile: open C:\Users\user\AppData\Roaming\verthash-ocm\dogekeyfile.hex: The system cannot find the file specified.
2021/06/09 17:27:17.943748 [INFO] Checking wallet..
2021/06/09 17:27:17.943748 [INFO] Initializing wallet DKpXfrpyT1UeC51ewdQaQq575Wzc4jcK2r
2021/06/09 17:27:17.943748 [INFO] Wallet initialized: 1
2021/06/09 17:27:18.283237 [DEBUG] GPU [NVIDIA GeForce GT 555M] matched regex [.*NVIDIA.*]
2021/06/09 17:27:18.588217 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/06/09 17:27:18.588217 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/06/09 17:27:18.588217 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/06/09 17:27:18.588217 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/06/09 17:27:18.588217 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/06/09 17:27:18.588217 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/06/09 17:27:18.588217 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/06/09 17:27:18.588217 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/06/09 17:27:18.588217 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/06/09 17:27:18.588217 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/06/09 17:27:18.588217 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/06/09 17:27:18.588217 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/06/09 17:27:18.590235 [DEBUG] [Miner windows/2]Binary not found, downloading...
2021/06/09 17:27:19.518490 [DEBUG] [Miner windows/2]Daemon file downloaded
2021/06/09 17:27:19.525148 [DEBUG] [Miner windows/2]Daemon file is available and correct
2021/06/09 17:27:19.525653 [DEBUG] [Miner windows/2](Re)creating unpack directory
2021/06/09 17:41:04.631355 [DEBUG] Launching C:\Users\user\AppData\Roaming\verthash-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\user\AppData\Roaming\verthash-ocm\verthash-miner-tmpl.conf]
2021/06/09 17:41:04.810740 [DEBUG]Entering device block
2021/06/09 17:41:04.810740 [DEBUG]Exiting device block
2021/06/09 17:41:04.811247 [DEBUG]{0  false  }
2021/06/09 17:41:04.811247 [DEBUG]Entering device block
2021/06/09 17:41:04.811247 [DEBUG]Exiting device block
2021/06/09 17:41:04.811247 [DEBUG]{0  false  }
2021/06/09 17:41:04.811402 [DEBUG] AvailableGPUs called
2021/06/09 17:41:04.812166 [DEBUG] Launching C:\Users\user\AppData\Roaming\verthash-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\user\AppData\Roaming\verthash-ocm\verthash-miner-tmp.conf]
2021/06/09 18:13:29.195089 [INFO] Setting closed source to [%!b(bool=false)]
2021/06/09 18:13:29.198869 [INFO] Setting debugging to [%!b(bool=false)]
2021/06/09 18:13:29.715942 [INFO] Setting custom address to []
2021/06/09 18:13:30.269686 [INFO] Stopping mining process...
2021/06/09 18:13:30.640535 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/06/09 18:13:30.640535 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/06/09 18:13:30.640535 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/06/09 18:13:30.640535 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/06/09 18:13:30.640535 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/06/09 18:13:30.640535 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/06/09 18:13:30.640535 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/06/09 18:13:30.640535 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/06/09 18:13:30.640535 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/06/09 18:13:30.640535 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/06/09 18:13:30.640535 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/06/09 18:13:30.640535 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/06/09 18:13:30.640535 [DEBUG] [Miner windows/2]Daemon file already exists
2021/06/09 18:13:30.646538 [DEBUG] [Miner windows/2]Daemon file is available and correct
2021/06/09 18:13:30.646538 [DEBUG] [Miner windows/2]Removing unpack directory
2021/06/09 18:13:31.654837 [DEBUG] [Miner windows/2](Re)creating unpack directory
2021/06/09 18:13:41.739937 [DEBUG] Launching C:\Users\user\AppData\Roaming\verthash-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\user\AppData\Roaming\verthash-ocm\verthash-miner-tmpl.conf]
2021/06/09 18:13:41.851186 [DEBUG]Entering device block
2021/06/09 18:13:41.851186 [DEBUG]Exiting device block
2021/06/09 18:13:41.851186 [DEBUG]{0  false  }
2021/06/09 18:13:41.851186 [DEBUG]Entering device block
2021/06/09 18:13:41.851186 [DEBUG]Exiting device block
2021/06/09 18:13:41.851186 [DEBUG]{0  false  }
2021/06/09 18:13:41.851729 [DEBUG] AvailableGPUs called
2021/06/09 18:13:41.852273 [DEBUG] Launching C:\Users\user\AppData\Roaming\verthash-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\user\AppData\Roaming\verthash-ocm\verthash-miner-tmp.conf]
2021/06/09 18:24:16.551121 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/06/09 18:24:16.551628 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/06/09 18:24:16.551628 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/06/09 18:24:16.551628 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/06/09 18:24:16.551702 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/06/09 18:24:16.551702 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/06/09 18:24:16.551702 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/06/09 18:24:16.551702 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/06/09 18:24:16.551702 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/06/09 18:24:16.551702 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/06/09 18:24:16.551702 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/06/09 18:24:16.551785 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/06/09 18:24:16.551937 [DEBUG] [Miner windows/2]Daemon file already exists
2021/06/09 18:24:16.558695 [DEBUG] [Miner windows/2]Daemon file is available and correct
2021/06/09 18:24:16.558695 [DEBUG] [Miner windows/2]Removing unpack directory
2021/06/09 18:24:17.561364 [DEBUG] [Miner windows/2](Re)creating unpack directory
2021/06/09 18:24:27.938043 [DEBUG] Launching C:\Users\user\AppData\Roaming\verthash-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\user\AppData\Roaming\verthash-ocm\verthash-miner-tmpl.conf]
2021/06/09 18:24:28.043009 [DEBUG]Entering device block
2021/06/09 18:24:28.043009 [DEBUG]Exiting device block
2021/06/09 18:24:28.043009 [DEBUG]{0  false  }
2021/06/09 18:24:28.043009 [DEBUG]Entering device block
2021/06/09 18:24:28.043009 [DEBUG]Exiting device block
2021/06/09 18:24:28.043009 [DEBUG]{0  false  }
2021/06/09 18:24:28.043542 [DEBUG] AvailableGPUs called
2021/06/09 18:24:28.044123 [DEBUG] Launching C:\Users\user\AppData\Roaming\verthash-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\user\AppData\Roaming\verthash-ocm\verthash-miner-tmp.conf]
2021/06/09 18:35:49.909276 [INFO] Setting closed source to [%!b(bool=false)]
2021/06/09 18:35:49.909276 [INFO] Setting debugging to [%!b(bool=true)]
2021/06/09 18:35:50.179630 [INFO] Setting custom address to []
2021/06/09 18:35:50.595876 [INFO] Stopping mining process...
2021/06/09 18:35:51.769935 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/06/09 18:35:51.769935 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/06/09 18:35:51.769935 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/06/09 18:35:51.769935 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/06/09 18:35:51.769935 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/06/09 18:35:51.769935 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/06/09 18:35:51.769935 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/06/09 18:35:51.769935 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/06/09 18:35:51.769935 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/06/09 18:35:51.769935 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/06/09 18:35:51.769935 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/06/09 18:35:51.769935 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/06/09 18:35:51.769935 [DEBUG] [Miner windows/2]Daemon file already exists
2021/06/09 18:35:51.776940 [DEBUG] [Miner windows/2]Daemon file is available and correct
2021/06/09 18:35:51.776940 [DEBUG] [Miner windows/2]Removing unpack directory
2021/06/09 18:35:52.789098 [DEBUG] [Miner windows/2](Re)creating unpack directory
2021/06/09 18:36:03.250424 [DEBUG] Launching C:\Users\user\AppData\Roaming\verthash-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\user\AppData\Roaming\verthash-ocm\verthash-miner-tmpl.conf]
2021/06/09 18:36:03.338231 [DEBUG] [VerthashMiner] [2021-06-09 18:36:03] INFO  Found 0 OpenCL devices.
2021/06/09 18:36:03.339465 [DEBUG] [VerthashMiner] [2021-06-09 18:36:03] WARN  Failed to initialize CUDA. error code: 35
2021/06/09 18:36:03.339465 [DEBUG] [VerthashMiner] [2021-06-09 18:36:03] WARN  CUDA devices will be unavailable.
2021/06/09 18:36:03.340531 [DEBUG] [VerthashMiner] [2021-06-09 18:36:03] INFO  Configuration file: (C:\Users\user\AppData\Roaming\verthash-ocm\verthash-miner-tmpl.conf) has been generated.
2021/06/09 18:36:03.359880 [DEBUG]Entering device block
2021/06/09 18:36:03.360432 [DEBUG]Exiting device block
2021/06/09 18:36:03.360432 [DEBUG]{0  false  }
2021/06/09 18:36:03.360432 [DEBUG]Entering device block
2021/06/09 18:36:03.360432 [DEBUG]Exiting device block
2021/06/09 18:36:03.360432 [DEBUG]{0  false  }
2021/06/09 18:36:03.360432 [DEBUG] AvailableGPUs called
2021/06/09 18:36:03.361590 [DEBUG] Launching C:\Users\user\AppData\Roaming\verthash-ocm\miners\unpacked-e5af5ab19154f6ee57db22645a43200336e8017865c71505ae669af19243449e\VerthashMiner-0.7.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\user\AppData\Roaming\verthash-ocm\verthash-miner-tmp.conf]
2021/06/09 18:36:03.442677 [DEBUG] [VerthashMiner] [2021-06-09 18:36:03] INFO  Found 0 OpenCL devices.
2021/06/09 18:36:03.443765 [DEBUG] [VerthashMiner] [2021-06-09 18:36:03] WARN  Failed to initialize CUDA. error code: 35
2021/06/09 18:36:03.443765 [DEBUG] [VerthashMiner] [2021-06-09 18:36:03] WARN  CUDA devices will be unavailable.
2021/06/09 18:36:03.444313 [DEBUG] [VerthashMiner] [2021-06-09 18:36:03] INFO  Configuration file: (C:\Users\user\AppData\Roaming\verthash-ocm\verthash-miner-tmp.conf) has been generated.

**Comment by vertiond** [comment]
[Not supported](https://github.com/vertiond/verthash-one-click-miner#which-gpus-are-supported)
