### ISSUE TITLE
coin not going to wallet

### ISSUE THREAD

**Issue by Rebel2000** [vertiond/verthash-one-click-miner#34]
I moved coins from the hashcrypto wallet to another wallet and it removed them from my vertcoin miner but it never deposited to my other crypto wallet
 My mined coins to go to wallet

 it took coins from hashcrypto and never moved to other wallet

not sure 

github 

win 10 1050ti

**Comment by vertiond** [comment]
Are you saying that you had Dogecoin in your Spendable Balance on Verthash Miner which you sent to another wallet?

**Comment by Rebel2000** [comment]
Yes it was around 2.5 doge and after the fee should've been 1.5 doge.  I was trying to make sure everything went smoothly before I continued mining.  It never went through though.   I did successfully transfer some tonight that went through.  Maybe it was a minimum deposit rule or something but it did take it from my verthash.  Sent to a wallet on the crypto.com app both times.   
 
  On Mon, Jun 14, 2021 at 11:07 PM, ***@***.***> wrote:   


Are you saying that you had Dogecoin in your Spendable Balance on Verthash Miner which you sent to another wallet?

**Comment by vertiond** [comment]
That first transaction should be visible on a block explorer or the balance included in the following transaction if it somehow failed.
