### ISSUE TITLE
miner software reported no compatible gpu, I am using palit gt 730 2gb ddr3 128bit

### ISSUE THREAD

**Issue by minerpoor** [vertiond/verthash-one-click-miner#39]
![Untitled](https://user-images.githubusercontent.com/87263251/125191034-fd5fdf80-e272-11eb-94f6-8efa291c7e0a.jpg)

**Comment by Lordstarr1** [comment]
@minerpoor Yeah the DDR3 version of the GT 730 is not compatible with the algorithm. you would need a GDDR5 version. 

    AMD GPU GCN 1.0 or later.
    NVIDIA GPU with compute capability 3.0 or later.
    (Some compute versions may require different miner builds for the CUDA backend. e.g 8.0 requires CUDA 11.0, which removes support for 3.0.)

https://developer.nvidia.com/cuda-gpus#compute

**Comment by minerpoor** [comment]
Thank you for your reply. Any suggestions sir and chance to use this old
gpu for mining? I really appreciate your response.

**Comment by Lordstarr1** [comment]
No, I do not know of anything it will work with. Sorry.

**Comment by minerpoor** [comment]
Thanks for the tip!
