### ISSUE TITLE
Verthash OCM runs on both iGpu and Dgpu

### ISSUE THREAD

**Issue by SomeNoob7** [vertiond/verthash-one-click-miner#45]
Verthash OCM runs on both iGpu and dGpu regardless of the unchecked "Mine on integrated graphics" option making my laptop insanely lag :/

Im expecting Verthash OCM to only mine on dGpu.

It mines on both iGpu and dGpu.

The issue happens when you start mining,

Version: OCM v2.0-rc8-3eab099
Website: https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbjVsSWRLR1lJUmJISWIyWDUtcXM5WUVWcDBIZ3xBQ3Jtc0trX3pESXBidDZ4NW4xeE1ZNjBnZVY1VHhvVWREQ1FlazkydTRkU1VCLUZwVGVtM3ZqdkQ5UEZQbmR4ZVZWOGZkMDNValFFVHF5X0twOEhKalF2SHpVM1dSNWMzYjVCUVJ0SWs2c2lrdG0wLXUyRXo5Zw&q=https%3A%2F%2Fgithub.com%2Fvertiond%2Fverthash-one-click-miner%2Freleases%2Flatest

OS: WIN10
OS build: 19042.1110
Version: 20H2

iGpu: Vega8
dGpu: GTX1050M (4GB)

**Comment by vertiond** [comment]
This software isn't really designed for running on laptops and it may not be possible to isolate those components unfortunately.  In any regard, mining on a laptop is ill advised due to poor cooling capabilities.
