### ISSUE TITLE
the app one click minner is not minning properly 

### ISSUE THREAD

**Issue by ahmedhegazy225** [vertiond/verthash-one-click-miner#50]
My hash rate is .240 doge per day and since yesterday I didn't get but .400000 dogie please assist

**Comment by vertiond** [comment]
Can you elaborate?

**Comment by ahmedhegazy225** [comment]
I mine for the whole day and i only get 1/6 of the expected hash rate that was the issue , but for now i am supposed to mine the 1 doge in 4 days and 6 hours but it takes much time than that can you please advice

**Comment by vertiond** [comment]
You may have too low of hash rate and having difficulty finding shares.  There isn't anything I can do.

**Comment by ahmedhegazy225** [comment]
[](url)
![Screenshot 2021-08-11 011251](https://user-images.githubusercontent.com/21988713/128946868-938db1ea-d99b-4c12-83ae-9e6a6952ade1.jpg)
then the expected earning per day is not accurate means that I can't depend on it

**Comment by vertiond** [comment]
That would be on the pool for giving you too high difficulty of shares.  Sorry, this is not a problem with the OCM.
