### ISSUE TITLE
Miner software reported no GPU

### ISSUE THREAD

**Issue by iamsuvhro** [vertiond/verthash-one-click-miner#53]
Miner software reported no GPU

Miner software reported no GPU

Miner software reported no GPU

Miner software reported no GPU

Miner software reported no GPU

Miner software reported no GPU

**Comment by vertiond** [comment]
Read [FAQ](https://github.com/vertiond/verthash-one-click-miner#my-gpu-is-supported-but-an-error-messages-reads-no-compatible-gpus)
