### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by Ig2600** [vertiond/verthash-one-click-miner#70]
I can't send the payment to my Binance account

Transfer the payment for mining without any issues

![Sin títulofd](https://user-images.githubusercontent.com/93160862/138767891-910cd691-7c95-4ed3-98f4-26a8102cfee5.png)

I have almost one week trying to send the payment, and the app keeps launching the same error: sendind.backend_error

OCM v2.0-rc6-29b0e12

Windows 10. GTX 1060 3GB

no

**Comment by vertiond** [comment]
Upgrade to the latest release and re-open if the issue persists.
