### ISSUE TITLE
checks failed

### ISSUE THREAD

**Issue by MaxRSTC** [vertiond/verthash-one-click-miner#74]
![image](https://user-images.githubusercontent.com/69337297/140469591-6bb281ca-f6d6-4b31-968c-2065a4052253.png)

**Comment by MaxRSTC** [comment]
Could you please explain how to fix this problem?

**Comment by vertiond** [comment]
Restart the application and if the issue persists, delete the folder containing `VerthashMiner.exe` within `%appdata%\verthash-ocm`.
