### ISSUE TITLE
Verthash Problem

### ISSUE THREAD

**Issue by Devestator77** [vertiond/verthash-one-click-miner#75]
I downloaded Vertcoin one click miner yesterday and also created a password. Since yesterday I have been getting the message: "Could not find comptible of my binaries".
I have now looked at google and youtube or questioned but got no results.

Please Help
![Vertcoin](https://user-images.githubusercontent.com/93983054/140924516-9f8ce15e-62ac-4959-81ca-e07dcfd72d84.JPG)

**Comment by KforG** [comment]
Assuming your GPU is compatible you may need to exclude the miner, which is located in `%appdata%\verthash-ocm` . If the miner is being blocked by your antivirus from detecting your GPU, it will not be able to figure out which start commands are to be used.
