### ISSUE TITLE
Failure to configure VerthashMiner.exe

### ISSUE THREAD

**Issue by sexyannielou** [vertiond/verthash-one-click-miner#76]
The miner dont want to launch

to start the miner after configuring it 

![Capture](https://user-images.githubusercontent.com/94106465/141268123-4ac7e129-c957-4aaa-9e1c-395322a81a55.PNG)

OCM V2.0

Windows 7 x64 Nvidia geforce GT710

i dont have any firewall and the app is autorized by win Firewall

%APPDATA%\vertcoin-ocm on Windows
$HOME/.vertcoin-ocm on Linux

-->

**Comment by vertiond** [comment]
This is related to permissions and is usually the cause of an incorrect firewall configuration.  You may have to additionally exclude the `%appdata%\verthash-ocm`.
