### ISSUE TITLE
pagamento  pela pool pendente

### ISSUE THREAD

**Issue by mateusmarques009** [vertiond/verthash-one-click-miner#77]
<bom dia minha mineração só fica pendente.

eu gostaria de sacar  como que eu faço ???

já tem muito tempo que esta pendente!

minha mineração está com 
quantidades disponível

0.0000000000 DOGE 
(11.08888260 RVN pagamento  pela pool pendente)

Como devo proceder para saca? qual o valor mínimo?>

**Comment by KforG** [comment]
The pools minimum payout will be displayed on the pools website.

If you're using Zergpool, this is taken from their front page:

> DOGE payouts are made automatically every 4 hours for all balances above 50, or 10 on Sunday.
