### ISSUE TITLE
available balance  zero .

### ISSUE THREAD

**Issue by JOSE01X** [vertiond/verthash-one-click-miner#78]
hello I have been using verthash-one-click-miner for some time without any problem, every Sunday the mine was credited in doge to available balance, and then I withdrawn it to another wallet, since Sunday, September 24, my available balance will appear in zero, and the following Sundays equal to zero, I should already have 61.54 doge in available balance and it remains at zero, you can tell me what I should do to solve my problem. I am using windows 10, and as I mentioned before having problems, everything had worked fine. I understand that verthash-one-click-miner works like a wallet, it will be that some kind of synchronization is missing for my available balance to come out.
![I1](https://user-images.githubusercontent.com/94498168/142093601-3aedd9cd-b75b-44fe-a885-0d301d0b0625.png)
![I2](https://user-images.githubusercontent.com/94498168/142093610-d03d215c-11ec-4e88-a89b-fb7ad1428555.png)
![I3](https://user-images.githubusercontent.com/94498168/142093621-bc1ce5c4-4453-45bc-b4c2-0813af6905fd.png)

**Comment by vertiond** [comment]
Update to the latest version.

**Comment by JOSE01X** [comment]
Hello, download the last version that I found on the official page Varthash-One-Click-Miner, the diponible balance is still at zero, some other idea, everything works well, only that the Pool payment is not available in the VERTHASH-ONE application -Click-Miner, it seems to me that it would be a problem of wallet synchronization and I do not know how to solve it.
![I4](https://user-images.githubusercontent.com/94498168/142739540-42a6c62a-1c12-403b-8f23-a88e7e6c415c.png)

**Comment by vertiond** [comment]
The address balance is fetched from Sochain's API so I am guessing that your computer or network is somehow blocking that connection.  First ensure that the program, `verthash-ocm.exe`, and maybe even the data directory, `%appdata%\verthash-ocm` are excluded from your antivirus / Windows Defender.  If the problem persists and you can't figure out your networking issue, then all I can suggest is for you to copy `dogekeyfile.hex` (this file is your encrypted wallet) from `%appdata%\verthash-ocm` to the same folder on another machine preferably outside of your network and try again.

**Comment by ConfusedManbird** [comment]
zergpool didn't send the coin to wallets, the pool wallet has tons of doge, I think its zergpool's fault
