### ISSUE TITLE
Checks failed error

### ISSUE THREAD

**Issue by wazorkor** [vertiond/verthash-one-click-miner#80]
getting a checks failed error stating one or more of my miners are showing rapid failures.Followed subsequent steps but its not solving the issue. 
Mining DGB w Verthash

start mining

**Comment by vertiond** [comment]
This might be an issue with Zergpool.  I would temporarily switch pools until the issue is resolved.

**Comment by xMOXIEx** [comment]
I am having the same issue mining Vertcoin getting paid in ETH using Zergpool... The issue just started today on 2 different PC's
![Zergpool Issue](https://user-images.githubusercontent.com/53958454/142750087-5570d97c-8fa7-4dce-831c-89410d09a4a8.PNG)

**Comment by wazorkor** [comment]
thanks a ton for the reply - is there another pool that I'm able to mine DBG with? i've played around w it and haven't found anything similar to Zergpool yet 
    On Saturday, November 20, 2021, 04:59:02 AM PST, vertion ***@***.***> wrote:  
 
 


This might be an issue with Zergpool. I would temporarily switch pools until the issue is resolved.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vertiond** [comment]
zpool.ca, it's in the latest release.
