### ISSUE TITLE
Allow use of existing doge address

### ISSUE THREAD

**Issue by ConfusedManbird** [vertiond/verthash-one-click-miner#84]
### Feature Request
* allow use of existing doge address; on all other coins you can set a receiving address, which automates payout. 

   
and thank you, this app has made me alot of money

**Comment by vertiond** [comment]
I've decided to not include this feature as long as the program has a built in Dogecoin wallet.  The final 1.0 release has this feature and will have the same mining performance as the current version. https://github.com/vertiond/verthash-one-click-miner/releases/tag/1.0
