### ISSUE TITLE
Verthash OCM 20. Rc-8 has suddendly stopped mining.

### ISSUE THREAD

**Issue by Kaushikkrsaikia** [vertiond/verthash-one-click-miner#86]
The verthash ocm 2.0 rc-8 has suddenly stopped working after a long time.
 Even there is a error when we restart it it should start mining again which didn't happen in my case.

actual behaviour was it used mine fine. But suddenly at 90 of ethereum payout it had stopped working

verthash ocm 2.0 rc-8

 gpu

**Comment by vertiond** [comment]
This is most often the cause of a Windows update.  Revisit your firewall exclusions, you may have to exclude the %appdata%\verthash-ocm folder in addition.

**Comment by Kaushikkrsaikia** [comment]
Hi,
I have tried excluding the %appdata%\verthash-ocm folder in addition but it
didn't solve the problem. Kindly suggest a working solution.
Regard's
Kaushik

**Comment by vertiond** [comment]
Update and read the FAQ.  For further support, join the Vertcoin discord. https://discord.gg/vertcoin
