### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by Dhanushryadav** [vertiond/verthash-one-click-miner#96]

**Comment by Dhanushryadav** [comment]
my miner having binary issue all of a sudden ad asking to enable debugging. someone help me out with this issue
![vsrthash](https://user-images.githubusercontent.com/99545713/153717037-c4237f62-1a30-4287-85fd-6089102fdf92.png)

**Comment by vertiond** [comment]
Ensure your GPU is compatible, see FAQ

**Comment by Dhanushryadav** [comment]
I was mining from a month..yesterday I updated windows and now verthash is
showing like that..

**Comment by Dhanushryadav** [comment]
I enabled debugging in my pc..but also showing the same..

**Comment by Dhanushryadav** [comment]
Sir/Ma'am, Do you have another communicating platforms coz i'm not getting
how to raise an issue in github or communicate in that.
Requesting for your help..

**Comment by vertiond** [comment]
This might be an issue involving stratum connections on Zergpool by VerthashMiner, the open-source miner that this program utilizes.  Please join the discord for further support.  https://discord.gg/vertcoin
