### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by Hippie4200** [vertiond/verthash-one-click-miner#97]
#95 IS NOT resolved. Please help me

**Comment by vertiond** [comment]
Type `%AppData%\verthash-ocm` into your file explorer search bar and hit enter.  Delete this folder.

**Comment by Hippie4200** [comment]
> Type `%AppData%\verthash-ocm` into your file explorer search bar and hit enter. Delete this folder.

nothing shows up yet the app still starts when i turn my pc on. whys that?

**Comment by Hippie4200** [comment]
i will look into how to do that and try. please keep this open tysm

**Comment by Hippie4200** [comment]
i think i got everything.

my issue was when i restarted my pc, the app launched. I took the check off
"launch when start" and did a system restore.
